Solution of Assignment
p-paf/99problems pull request #3
Opened 2020-03-16 06:30 UTC by SARTHAKKRSHARMA

2020-03-16 06:32 UTC, SARTHAKKRSHARMA commented
It was fun working on this assignment.

2020-03-19 10:19 UTC, 7vik requested changes
Great Job! Have you created your own directory as suggested in the instructions? @SARTHAKKRSHARMA

2020-03-21 06:21 UTC, twitu commented
@SARTHAKKRSHARMA please move all your files to a single directory, as mentioned in the instructions. I can merge your PR after that.

2020-03-21 06:28 UTC, twitu commented on Problem3.hs
> +
Try to come up with one more solution to this problem, as a hint you can create a function called,
`elementAt :: [a] -> Int -> a` that actually calls another function that has a slightly different type signature namely,
`actualElementAt :: ([a], Int) -> Int -> a`.

2020-03-21 06:28 UTC, twitu commented on Problem3.hs
> +
On the other hand you could use an approach similar to the `myLength` function.

2020-03-21 06:28 UTC, twitu commented on Problem6.hs
> +    | ord 'A' <= ord ch && ord 'Z' >= ord ch  = chr (ord ch + ord 'a' - ord 'A')
Look for a function with type signature `Char -> Char` in https://hoogle.haskell.org/, it might give you some ideas ;)

2020-03-23 05:20 UTC, twitu commented
The suggested improvements in code are something you can do in time. However I need you to move your files to a single folder to merge the request.

2020-03-23 07:18 UTC, SARTHAKKRSHARMA commented
I have tried to move them under one directory but I'm not sure I have done
it correctly.

On Mon, Mar 23, 2020, 10:50 AM Ishan Bhanuka <notifications@github.com>
wrote:

> The suggested improvements in code are something you can do in time.
> However I need you to move your files to a single folder to merge the
> request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/p-paf/99problems/pull/3#issuecomment-602391365>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOBGUKIZLQEVUHF5W5GG763RI3WSPANCNFSM4LL2GWUQ>
> .
>

2020-03-23 08:29 UTC, twitu commented
Cmon, friend at least think of what you are doing? Change `Folder1` to your name so I can at least identify your code later.

2020-03-23 10:04 UTC, twitu approved these changes

2020-03-23 10:04 UTC, merged

2020-03-23 10:05 UTC, twitu commented
You still have a few changes to make namely,
1. adding better implementations
2. naming all the files starting with capital P `Problem..` as per convention.

You can submit that as a separate PR.

2020-03-23 10:40 UTC, SARTHAKKRSHARMA commented
How can I make better implementations?


On Mon, Mar 23, 2020, 3:35 PM Ishan Bhanuka <notifications@github.com>
wrote:

> You still have a few changes to make namely,
>
>    1. adding better implementations
>    2. naming all the files starting with capital P Problem.. as per
>    convention.
>
> You can submit that as a separate PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/p-paf/99problems/pull/3#issuecomment-602498087>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOBGUKN72HVEQXIPK5Z2F73RI4X7TANCNFSM4LL2GWUQ>
> .
>

2020-03-23 10:42 UTC, twitu commented
I mean add more implementations as mentioned in the previous comments.

On Mon, Mar 23, 2020, 4:11 PM SARTHAKKRSHARMA <notifications@github.com>
wrote:

> How can I make better implementations?
>
>
> On Mon, Mar 23, 2020, 3:35 PM Ishan Bhanuka <notifications@github.com>
> wrote:
>
> > You still have a few changes to make namely,
> >
> > 1. adding better implementations
> > 2. naming all the files starting with capital P Problem.. as per
> > convention.
> >
> > You can submit that as a separate PR.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/p-paf/99problems/pull/3#issuecomment-602498087>, or
> > unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AOBGUKN72HVEQXIPK5Z2F73RI4X7TANCNFSM4LL2GWUQ
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/p-paf/99problems/pull/3#issuecomment-602514993>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFQ7JWTEKVOLLO3MOY22WTLRI44EJANCNFSM4LL2GWUQ>
> .
>

2020-03-23 10:45 UTC, SARTHAKKRSHARMA commented
Surely I will.

On Mon, Mar 23, 2020, 4:13 PM Ishan Bhanuka <notifications@github.com>
wrote:

> I mean add more implementations as mentioned in the previous comments.
>
> On Mon, Mar 23, 2020, 4:11 PM SARTHAKKRSHARMA <notifications@github.com>
> wrote:
>
> > How can I make better implementations?
> >
> >
> > On Mon, Mar 23, 2020, 3:35 PM Ishan Bhanuka <notifications@github.com>
> > wrote:
> >
> > > You still have a few changes to make namely,
> > >
> > > 1. adding better implementations
> > > 2. naming all the files starting with capital P Problem.. as per
> > > convention.
> > >
> > > You can submit that as a separate PR.
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/p-paf/99problems/pull/3#issuecomment-602498087>,
> or
> > > unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AOBGUKN72HVEQXIPK5Z2F73RI4X7TANCNFSM4LL2GWUQ
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/p-paf/99problems/pull/3#issuecomment-602514993>, or
> > unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AFQ7JWTEKVOLLO3MOY22WTLRI44EJANCNFSM4LL2GWUQ
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/p-paf/99problems/pull/3#issuecomment-602515858>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOBGUKOSLVZOTH5BMFIC5QLRI44LTANCNFSM4LL2GWUQ>
> .
>